<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Weronika Jaszkiewicz">
<meta name="author" content="Dominik Hołoś">
<meta name="author" content="Weronika Pyrtak">
<meta name="author" content="Katarzyna Rudzińska">

<title>Analiza działalności firmy Space-U</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Raport_Bazy_Danych_files/libs/clipboard/clipboard.min.js"></script>
<script src="Raport_Bazy_Danych_files/libs/quarto-html/quarto.js"></script>
<script src="Raport_Bazy_Danych_files/libs/quarto-html/popper.min.js"></script>
<script src="Raport_Bazy_Danych_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Raport_Bazy_Danych_files/libs/quarto-html/anchor.min.js"></script>
<link href="Raport_Bazy_Danych_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Raport_Bazy_Danych_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Raport_Bazy_Danych_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Raport_Bazy_Danych_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Raport_Bazy_Danych_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="Raport_Bazy_Danych_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Raport_Bazy_Danych_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analiza działalności firmy Space-U</h1>
<p class="subtitle lead">Bazy Danych</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Weronika Jaszkiewicz </p>
             <p>Dominik Hołoś </p>
             <p>Weronika Pyrtak </p>
             <p>Katarzyna Rudzińska </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="wstęp-o-firmie" class="level1">
<h1>Wstęp o firmie</h1>
<p>Firma Space-U jest firmą turystyczną organizującą wyprawy kosmiczne, oferującą doświadczenie podróży między galaktycznych. Firma zatrudnia 62 pracowników na stanowiskach Technician, Pilot, Commander, Mission Specialist, Navigator i do tej pory obsłużyła 1000 klientów. Do dyspozycji firmy jest 20 rakiet. Firma oferuje 45 typów wypraw. Firma operuje w 5 galaktykach, w tym w 15 systemach planetarnych</p>
</section>
<section id="zawartość-raportu" class="level1">
<h1>Zawartość raportu</h1>
<p>Celem raportu było przeanalizowanie działalności firmy Space-U pod kątem rentowności wypraw, struktury kosztów, lojalności klientów, sezonowości oraz efektywności operacyjnej w różnych galaktykach i systemach planetarnych. Zadano następujące pytania analityczne:</p>
<ol type="1">
<li><p>Jakie wyprawy są najbardziej popularne i opłacalne?</p></li>
<li><p>Czy firma rośnie, czy traci klientów?</p></li>
<li><p>Jakie czynniki wpływają na powracalność klientów?</p></li>
<li><p>Czy wyprawy round-trip są bardziej popularne w określonych miejscach?</p></li>
<li><p>Czy pojemność rakiet wpływa na punktualność?</p></li>
<li><p>Jak wynagrodzenia pracowników wiążą się z wyprawami?</p></li>
<li><p>Które galaktyki i układy są najbardziej dochodowe?</p></li>
<li><p>Czy odległość od Ziemi wpływa na organizację wypraw?</p></li>
<li><p>Jakie są trendy sezonowe w działalności firmy?</p></li>
</ol>
</section>
<section id="najpopularniejsze-wyprawy---koszty-przychody-i-opłacalność" class="level1">
<h1>Najpopularniejsze wyprawy - koszty, przychody i opłacalność</h1>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabela 1. Zestawienie popularności, kosztów i zysków według rodzaju podróży</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">trip_type_id</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">trip_name</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bookings_count</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total_costs</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total_revenue</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">profit</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">profit_margin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: left;">Mission to Caelus</td>
<td style="text-align: right;">121</td>
<td style="text-align: right;">12617124.57</td>
<td style="text-align: right;">369821730</td>
<td style="text-align: right;">357204605</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">34</td>
<td style="text-align: left;">Mission to Heliora</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">927744.50</td>
<td style="text-align: right;">26976635</td>
<td style="text-align: right;">26048891</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: left;">Mission to Mnestra</td>
<td style="text-align: right;">119</td>
<td style="text-align: right;">1099196.78</td>
<td style="text-align: right;">29636356</td>
<td style="text-align: right;">28537160</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">36</td>
<td style="text-align: left;">Mission to Sibylla</td>
<td style="text-align: right;">115</td>
<td style="text-align: right;">823353.13</td>
<td style="text-align: right;">21398430</td>
<td style="text-align: right;">20575077</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Mission to Euryale</td>
<td style="text-align: right;">113</td>
<td style="text-align: right;">739066.13</td>
<td style="text-align: right;">17123445</td>
<td style="text-align: right;">16384378</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Mission to Notos</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">6180179.15</td>
<td style="text-align: right;">192022529</td>
<td style="text-align: right;">185842350</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: left;">Mission to Meliora</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">477678.83</td>
<td style="text-align: right;">12356239</td>
<td style="text-align: right;">11878561</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">27</td>
<td style="text-align: left;">Mission to Oenone</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">729016.13</td>
<td style="text-align: right;">20636205</td>
<td style="text-align: right;">19907189</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: right;">24</td>
<td style="text-align: left;">Mission to Eileithyia</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">343095.62</td>
<td style="text-align: right;">8477263</td>
<td style="text-align: right;">8134167</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">32</td>
<td style="text-align: left;">Mission to Thalia</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">444236.90</td>
<td style="text-align: right;">12044882</td>
<td style="text-align: right;">11600645</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: right;">37</td>
<td style="text-align: left;">Mission to Sterope</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">706868.76</td>
<td style="text-align: right;">23640847</td>
<td style="text-align: right;">22933978</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">33</td>
<td style="text-align: left;">Mission to Laelapsa</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">483237.82</td>
<td style="text-align: right;">12300358</td>
<td style="text-align: right;">11817121</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: left;">Mission to Alecto</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">1034831.05</td>
<td style="text-align: right;">25253351</td>
<td style="text-align: right;">24218520</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Mission to Rhea</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">547333.42</td>
<td style="text-align: right;">16312973</td>
<td style="text-align: right;">15765639</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Mission to Lemuria</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">4283618.52</td>
<td style="text-align: right;">129000366</td>
<td style="text-align: right;">124716747</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">30</td>
<td style="text-align: left;">Mission to Neoma</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">892507.13</td>
<td style="text-align: right;">24049701</td>
<td style="text-align: right;">23157194</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: right;">40</td>
<td style="text-align: left;">Mission to Rhenara</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">1103736.60</td>
<td style="text-align: right;">30273520</td>
<td style="text-align: right;">29169783</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">35</td>
<td style="text-align: left;">Mission to Iris</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">551709.44</td>
<td style="text-align: right;">13835264</td>
<td style="text-align: right;">13283555</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: right;">45</td>
<td style="text-align: left;">Mission to Idonea</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">985047.54</td>
<td style="text-align: right;">24250040</td>
<td style="text-align: right;">23264992</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: left;">Mission to Astraeus</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">2007537.30</td>
<td style="text-align: right;">64298254</td>
<td style="text-align: right;">62290716</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16</td>
<td style="text-align: left;">Mission to Mesembria</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">2541737.43</td>
<td style="text-align: right;">104203169</td>
<td style="text-align: right;">101661432</td>
<td style="text-align: right;">0.98</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Mission to Thyone</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">1206012.49</td>
<td style="text-align: right;">22326374</td>
<td style="text-align: right;">21120362</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="odd">
<td style="text-align: right;">43</td>
<td style="text-align: left;">Mission to Malina</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">370028.00</td>
<td style="text-align: right;">14101920</td>
<td style="text-align: right;">13731892</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">17</td>
<td style="text-align: left;">Mission to Harmonia</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">3103370.40</td>
<td style="text-align: right;">100357738</td>
<td style="text-align: right;">97254367</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Mission to Cerestra</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">143286.21</td>
<td style="text-align: right;">4080902</td>
<td style="text-align: right;">3937616</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">26</td>
<td style="text-align: left;">Mission to Hemera</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">132289.45</td>
<td style="text-align: right;">3732796</td>
<td style="text-align: right;">3600506</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20</td>
<td style="text-align: left;">Mission to Leto</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">300788.35</td>
<td style="text-align: right;">8492050</td>
<td style="text-align: right;">8191262</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">21</td>
<td style="text-align: left;">Mission to Metis</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">333248.93</td>
<td style="text-align: right;">9211757</td>
<td style="text-align: right;">8878508</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Mission to Eucharis</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">84710.69</td>
<td style="text-align: right;">1974244</td>
<td style="text-align: right;">1889533</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: right;">31</td>
<td style="text-align: left;">Mission to Vacuna</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">352564.65</td>
<td style="text-align: right;">8791772</td>
<td style="text-align: right;">8439207</td>
<td style="text-align: right;">0.96</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Tabela 1. przedstawia zestawienie danych dotyczących różnych typów podróży kosmicznych. Każdy wiersz odnosi się do konkretnego rodzaju podróży (<em>trip_name</em>). Kolumna <em>bookings_count</em> zawiera liczbę dokonanych rezerwacji, <em>total_costs</em> to całkowite koszty realizacji danego typu podróży, natomiast <em>total_revenue</em> przedstawia łączny przychód. Na tej podstawie wyliczono <em>profit</em> (czyli zysk netto: przychód minus koszty) oraz <em>profit_margin</em> – marżę zysku, wyrażoną jako udział zysku w przychodzie.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analiza danych rezerwacyjnych wskazuje, że największą popularnością wśród klientów cieszyły się wyprawy typu Mission to Caelus, Mission to Heliora, Mission to Mnestra, Mission to Sibylla, Mission to Euryale. Każda z nich miała od 113 do 121 rezerwacji, co potwierdza ich wysokie zainteresowanie na tle pozostałych ofert.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pod względem rentowności na czoło wysuwają się wyprawy:<br>
- Mission to Caelus : 357.20 mln USD zysku brutto<br>
- Mission to Heliora : 26.05 mln USD zysku brutto<br>
- Mission to Mnestra : 28.54 mln USD zysku brutto<br>
- Mission to Sibylla : 20.58 mln USD zysku brutto<br>
- Mission to Euryale : 16.38 mln USD zysku brutto</p>
<p>To pokazuje, że nie tylko popularność wpływa na opłacalność – ważna jest również struktura kosztów i cena jednostkowa. Co ciekawe, wiele wypraw z mniejszą liczbą rezerwacji (np.13 z 30) okazało się bardziej zyskownych niż te najbardziej uczęszczane.</p>
<p>Z drugiej strony, odnotowano kilka wypraw generujących straty – np. – ich koszty przewyższyły uzyskane przychody, a wskaźnik powrotu klientów po tych wyjazdach był zerowy. Wskazuje to jednoznacznie na potrzebę rewizji tych pozycji w ofercie.</p>
<p>Opłacalność wypraw zależy nie tylko od liczby klientów, ale przede wszystkim od właściwego zarządzania kosztami i odpowiedniego ustalenia cen. Warto skupić się na dalszym rozwijaniu wypraw o wysokiej rentowności i ograniczyć te, które przynoszą straty.</p>
</section>
<section id="dynamika-zmian-liczby-klientów-w-czasie" class="level1">
<h1>Dynamika zmian liczby klientów w czasie</h1>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabela 2. Suma przychodów, kosztów i liczba wypraw dla każdego typu wycieczki</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">trip_type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">trip_type_id</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total_income</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total_cost</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">count</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">profit</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">avg_profit_per_trip</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mission to Caelus</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1479286918</td>
<td style="text-align: right;">297791064</td>
<td style="text-align: right;">484</td>
<td style="text-align: right;">1181495854</td>
<td style="text-align: right;">2441107.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Heliora</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">107906540</td>
<td style="text-align: right;">23385308</td>
<td style="text-align: right;">480</td>
<td style="text-align: right;">84521232</td>
<td style="text-align: right;">176085.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Mnestra</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">118545425</td>
<td style="text-align: right;">25721445</td>
<td style="text-align: right;">476</td>
<td style="text-align: right;">92823981</td>
<td style="text-align: right;">195008.36</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Sibylla</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">85593722</td>
<td style="text-align: right;">19020064</td>
<td style="text-align: right;">460</td>
<td style="text-align: right;">66573657</td>
<td style="text-align: right;">144725.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Euryale</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">68493778</td>
<td style="text-align: right;">15591836</td>
<td style="text-align: right;">452</td>
<td style="text-align: right;">52901942</td>
<td style="text-align: right;">117039.70</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Notos</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">768090116</td>
<td style="text-align: right;">155163943</td>
<td style="text-align: right;">400</td>
<td style="text-align: right;">612926173</td>
<td style="text-align: right;">1532315.43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Meliora</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">49424957</td>
<td style="text-align: right;">11276952</td>
<td style="text-align: right;">372</td>
<td style="text-align: right;">38148006</td>
<td style="text-align: right;">102548.40</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Eileithyia</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">33909050</td>
<td style="text-align: right;">8304690</td>
<td style="text-align: right;">368</td>
<td style="text-align: right;">25604360</td>
<td style="text-align: right;">69577.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Oenone</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">82544819</td>
<td style="text-align: right;">17784964</td>
<td style="text-align: right;">368</td>
<td style="text-align: right;">64759855</td>
<td style="text-align: right;">175977.87</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Sterope</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">94563387</td>
<td style="text-align: right;">20172998</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">74390390</td>
<td style="text-align: right;">206639.97</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Thalia</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">48179527</td>
<td style="text-align: right;">10884146</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">37295381</td>
<td style="text-align: right;">103598.28</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Laelapsa</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">49201434</td>
<td style="text-align: right;">11291007</td>
<td style="text-align: right;">352</td>
<td style="text-align: right;">37910427</td>
<td style="text-align: right;">107700.08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Alecto</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">101013402</td>
<td style="text-align: right;">21290001</td>
<td style="text-align: right;">308</td>
<td style="text-align: right;">79723402</td>
<td style="text-align: right;">258842.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Rhea</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">65251891</td>
<td style="text-align: right;">14147819</td>
<td style="text-align: right;">304</td>
<td style="text-align: right;">51104073</td>
<td style="text-align: right;">168105.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Lemuria</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">516001462</td>
<td style="text-align: right;">104327892</td>
<td style="text-align: right;">284</td>
<td style="text-align: right;">411673570</td>
<td style="text-align: right;">1449554.83</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Neoma</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">96198805</td>
<td style="text-align: right;">20232801</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">75966005</td>
<td style="text-align: right;">271307.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Rhenara</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">121094080</td>
<td style="text-align: right;">25203296</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">95890784</td>
<td style="text-align: right;">352539.65</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Iris</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">55341056</td>
<td style="text-align: right;">12012131</td>
<td style="text-align: right;">264</td>
<td style="text-align: right;">43328926</td>
<td style="text-align: right;">164124.72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Idonea</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">97000158</td>
<td style="text-align: right;">20307592</td>
<td style="text-align: right;">252</td>
<td style="text-align: right;">76692567</td>
<td style="text-align: right;">304335.58</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Astraeus</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">257193014</td>
<td style="text-align: right;">52265083</td>
<td style="text-align: right;">212</td>
<td style="text-align: right;">204927931</td>
<td style="text-align: right;">966641.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Mesembria</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">416812676</td>
<td style="text-align: right;">83877335</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">332935341</td>
<td style="text-align: right;">2522237.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Malina</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">56407680</td>
<td style="text-align: right;">11840896</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">44566784</td>
<td style="text-align: right;">348178.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Thyone</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">89305496</td>
<td style="text-align: right;">18391019</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">70914477</td>
<td style="text-align: right;">554019.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Cerestra</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">16323608</td>
<td style="text-align: right;">3725441</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">12598167</td>
<td style="text-align: right;">121136.22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Harmonia</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">401430951</td>
<td style="text-align: right;">80687630</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">320743321</td>
<td style="text-align: right;">3084070.39</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Hemera</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">14931182</td>
<td style="text-align: right;">3307236</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">11623946</td>
<td style="text-align: right;">116239.46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Leto</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">33968201</td>
<td style="text-align: right;">7218920</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">26749281</td>
<td style="text-align: right;">278638.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Metis</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">36847027</td>
<td style="text-align: right;">7664725</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">29182301</td>
<td style="text-align: right;">317198.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mission to Eucharis</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7896977</td>
<td style="text-align: right;">1863635</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">6033341</td>
<td style="text-align: right;">68560.70</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mission to Vacuna</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">35167088</td>
<td style="text-align: right;">7403858</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">27763230</td>
<td style="text-align: right;">330514.65</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Tabela 2. przedstawia zestawienie finansowe dla różnych typów wycieczek kosmicznych, oznaczonych identyfikatorem <em>trip_type_id</em>. Kolumny <em>total_income</em> oraz <em>total_cost</em> przedstawiają łączne wartości przychodów i kosztów wygenerowanych przez każdy typ wycieczki. W kolumnie <em>count</em> znajduje się liczba zrealizowanych wypraw danego rodzaju. Na tej podstawie wyliczono wartość <em>profit</em> (czyli całkowity zysk) oraz <em>avg_profit_per_trip</em> — średni zysk przypadający na jedną wyprawę.</p>
<p>Zestawienie pokazuje łączny przychód, koszty i zyski brutto dla poszczególnych typów wypraw. Najwięcej wypraw przeprowadzono na planetę Caelus (484 wypraw), a najmniej w przypadku planety Vacuna (84 wypraw).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Wykres pokazuje średni zysk brutto przypadający na pojedynczą wyprawę dla każdego typu misji. Na jego podstawie widać, że wyprawy typu Mission to Harmonia, Mission to Mesembria, Mission to Caelus, Mission to Notos, Mission to Lemuria są pięcioma najbardziej dochodowymi. Z kolei wyprawy, które generują najniższy średni zysk (lub nawet straty), to Mission to Meliora, Mission to Eileithyia, Mission to Eucharis. Wskazuje to, że warto dokładnie przeanalizować ich opłacalność i ewentualnie rozważyć modyfikację oferty.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analiza miesięczna pokazuje, jak zmieniała się liczba obsłużonych klientów na przestrzeni czasu. Największy ruch zanotowano w wrzesień 2023, obsługując wtedy 184 unikalnych klientów. Z kolei najmniej klientów firma miała w lipiec 2023, tylko 19 osób.</p>
<p>Można zauważyć, że najchętniej wybieranym sezonem na wyprawy jest okres zimowo-wiosenny. Zmienność w liczbie klientów sugeruje potrzebę elastycznego zarządzania zasobami i wdrożenia sezonowych strategii cenowych.</p>
</section>
<section id="powracalność-klientów" class="level1">
<h1>Powracalność klientów</h1>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Na wykresie widać, które wycieczki budują lojalność klientów. Najlepiej wypadły: Mission to Vacuna, Mission to Sibylla, Mission to Euryale, Mission to Iris, Mission to Mnestra, Mission to Lemuria, Mission to Alecto, Mission to Rhenara, powyżej 0.64. Wysoka lojalność może wskazywać na unikalne doświadczenia, wysoki poziom satysfakcji lub atrakcyjną cenę. Warto zwrócić uwagę na wyprawy z niskim wskaźnikiem powrotu – poniżej 0.3 – takie jak Mission to Oenone, które wymagają dalszej analizy i ewentualnego dostosowania oferty.</p>
<p>Lojalność klientów powinna być kluczowym wskaźnikiem sukcesu wypraw – warto ją monitorować i budować programy retencji oparte na danych.</p>
</section>
<section id="porównanie-wycieczek-w-jedną-stronę-z-wycieczkami-tam-i-z-powrotem" class="level1">
<h1>Porównanie wycieczek w jedną stronę z wycieczkami “tam i z powrotem”</h1>
<p>Współczynnik round-trip ratio określa stosunek liczby podróży tam i z powrotem do liczby wypraw w jedną stronę. Jest liczony jako:</p>
<p><span class="math display">\[
\mathrm{round\_trip\_ratio} = \frac{\mathrm{round\_trip}}{\mathrm{one\_way} + 1}
\]</span></p>
<p>Użycie +1 w mianowniku zapobiega dzieleniu przez zero w przypadku braku podróży one-way.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Największy udział round-tripów odnotowano dla planety Euryale, gdzie współczynnik wyniósł 30. Świadczy to o ich atrakcyjności lub logistyce sprzyjającej podróżom powrotnym.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Cechy specjalne mają wpływ na preferencje dotyczące typu wypraw. Najwyższą medianę współczynnika round-trip zaobserwowano dla cechy lava_rivers. Sugeruje to, że planety zawierające tą cechę są atrakcyjne do wizyt powrotnych – być może ze względu na warunki sprzyjające krótkim, rekreacyjnym wyprawom.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Widoczna jest ujemna korelacja (-0.14) między długością orbity a skłonnością do wypraw typu round-trip,co oznacza, że dalsze planety rzadziej odwiedzane są z powrotem.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analiza wykazała, że planety z najwyższym współczynnikiem round-trip to m.in. Euryale, z maksymalnym wskaźnikiem 30. W przestrzeni najwięcej planet to te z 21 dominującymi round-trip, 7 dominującymi one-way i 2 zrównoważonymi wyprawami. Oznacza to, że różnorodność preferencji podróżnych jest wyraźnie widoczna i może wskazywać na zróżnicowane potrzeby oraz charakterystyki poszczególnych planet.</p>
<p>Wnioski te mogą być wykorzystane przy planowaniu nowych kierunków i tworzeniu elastycznych modeli podróży (np. mix one-way + return).</p>
</section>
<section id="wpływ-pojemności-rakiety-na-czynniki-podróży" class="level1">
<h1>Wpływ pojemności rakiety na czynniki podróży</h1>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabela 3. Dane dotyczące rakiet względem ich pojemności</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">capacity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total_clients</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total_flights</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">delayed_flights</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: right;">148</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: right;">380</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">233</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">481</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">223</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Tabela 3. prezentuje statystyki dotyczące rakiet w zależności od ich pojemności (<em>capacity</em>). W kolumnie <em>total_clients</em> podano łączną liczbę obsłużonych pasażerów, <em>total_flights</em> wskazuje liczbę zrealizowanych lotów, natomiast <em>delayed_flights</em> zawiera liczbę lotów, które wystąpiły z opóźnieniem. Dane pozwalają na ocenę efektywności i niezawodności rakiet o różnej pojemności.</p>
<p>Największą liczbę klientów przewieziono rakietami o pojemności 8, łączna liczba obsłużonych pasażerów wyniosła aż 481. Jeśli chodzi o liczbę odbytych lotów, przodowały rakiety o pojemności 8, wykonując 19 wypraw.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pod względem średniej liczby podróży przypadającej na jednego klienta, najwyższy wynik zanotowano dla pojemności 8. W tym przypadku, przeciętny klient korzystał z usług rakiety średnio 1.19 razy. Może to świadczyć o preferencjach bardziej zaangażowanych lub lojalnych klientów.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Z kolei w zestawieniu częstości opóźnień widać wyraźne różnice. Najniższy odsetek opóźnionych lotów dotyczył rakiet o pojemności 12, 11, 10, 8, 7, 5, 4, wynosząc 0%. Największy odsetek opóźnień przypadł na rakiety o pojemności 9, gdzie opóźnienia osiągnęły aż 18%.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Liczba klientów w zależności od pojemności pokazuje wyraźną tendencję: rakiety o większej pojemności obsługują więcej pasażerów. Największą popularnością cieszyły się maszyny o pojemności 8, które przewiozły łącznie 481 klientów. Mniejsze rakiety naturalnie miały mniejsze obłożenie, co jednak może być również efektem ich rzadszego wykorzystania w harmonogramie lotów.</p>
</section>
<section id="analiza-wynagrodzenia-pracowników-względem-uczęszczanych-wypraw" class="level1">
<h1>Analiza wynagrodzenia pracowników względem uczęszczanych wypraw</h1>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analiza liczby wystąpień ról pokazuje, które funkcje są kluczowe i najczęściej powtarzane. Wykres słupkowy pomaga zidentyfikować, że dominujące role to Navigator, Pilot. Oznacza to, że są to funkcje kluczowe operacyjnie, silnie związane z liczbą realizowanych wypraw.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analizując wykres pokazujący zarobki pracowników, w top 3 najlepiej zarabiającymi pracownikami są Michael Jones, Rebecca Jennings, Kimberly Mendez, którzy zarabiają między 12,500 a 13,300 USD. Zajmują oni stanowiska Commander.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Porównując wykresy dotyczące liczby wypraw per rola oraz poziomu zarobków, widać dodatnia korelacja (0.09) między zaangażowaniem w wyprawy a poziomem wynagrodzenia. Oznacza to, że funkcje częściej wykorzystywane w misjach są także lepiej opłacane. Wskazuje to na dobrze dostosowaną strukturę płac do potrzeb operacyjnych.</p>
</section>
<section id="wpływ-lokalizacji-planet-na-zyskowność-wypraw-oraz-związek-między-odległością-od-ziemi-a-ich-częstotliwością" class="level1">
<h1>Wpływ lokalizacji planet na zyskowność wypraw oraz związek między odległością od Ziemi a ich częstotliwością</h1>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabela 4. Top 10 układów planetarnych wg zysku netto</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">galaxy_name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">planetary_system</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">planetary_system_id</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">num_trips</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">total_cost</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">total_revenue</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">avg_planet_distance</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">net_profit</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">profit_per_trip</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Polaris Nexus</td>
<td style="text-align: left;">Neptunus</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1536</td>
<td style="text-align: left;">804,237,911</td>
<td style="text-align: left;">3,990,576,761</td>
<td style="text-align: right;">948.3791</td>
<td style="text-align: left;">3,186,338,850</td>
<td style="text-align: right;">2074439.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Polaris Nexus</td>
<td style="text-align: left;">Trion</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4272</td>
<td style="text-align: left;">764,041,734</td>
<td style="text-align: left;">3,735,145,467</td>
<td style="text-align: right;">919.8815</td>
<td style="text-align: left;">2,971,103,733</td>
<td style="text-align: right;">695483.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Omega Verge</td>
<td style="text-align: left;">Phantos</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">800</td>
<td style="text-align: left;">351,626,203</td>
<td style="text-align: left;">1,741,596,609</td>
<td style="text-align: right;">1007.0218</td>
<td style="text-align: left;">1,389,970,406</td>
<td style="text-align: right;">1737463.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kronis Ring</td>
<td style="text-align: left;">Ilyssar</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">396</td>
<td style="text-align: left;">251,632,006</td>
<td style="text-align: left;">1,250,438,029</td>
<td style="text-align: right;">497.3275</td>
<td style="text-align: left;">998,806,023</td>
<td style="text-align: right;">2522237.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Polaris Nexus</td>
<td style="text-align: left;">Axioma</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2064</td>
<td style="text-align: left;">233,959,583</td>
<td style="text-align: left;">1,127,215,319</td>
<td style="text-align: right;">995.4469</td>
<td style="text-align: left;">893,255,736</td>
<td style="text-align: right;">432778.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Virelia Cluster</td>
<td style="text-align: left;">Liora</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">2548</td>
<td style="text-align: left;">193,456,609</td>
<td style="text-align: left;">919,561,254</td>
<td style="text-align: right;">567.0335</td>
<td style="text-align: left;">726,104,645</td>
<td style="text-align: right;">284970.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zerion Reach</td>
<td style="text-align: left;">Typhonis</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">3612</td>
<td style="text-align: left;">163,252,509</td>
<td style="text-align: left;">746,523,955</td>
<td style="text-align: right;">744.0998</td>
<td style="text-align: left;">583,271,447</td>
<td style="text-align: right;">161481.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Omega Verge</td>
<td style="text-align: left;">Aether</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2000</td>
<td style="text-align: left;">144,773,630</td>
<td style="text-align: left;">689,302,145</td>
<td style="text-align: right;">866.5890</td>
<td style="text-align: left;">544,528,515</td>
<td style="text-align: right;">272264.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zerion Reach</td>
<td style="text-align: left;">Liora</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">2520</td>
<td style="text-align: left;">141,210,985</td>
<td style="text-align: left;">661,943,712</td>
<td style="text-align: right;">567.0335</td>
<td style="text-align: left;">520,732,727</td>
<td style="text-align: right;">206640.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zerion Reach</td>
<td style="text-align: left;">Sagitta</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">1520</td>
<td style="text-align: left;">128,593,950</td>
<td style="text-align: left;">613,631,352</td>
<td style="text-align: right;">725.8010</td>
<td style="text-align: left;">485,037,402</td>
<td style="text-align: right;">319103.5</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Tabela 4. pokazuje 10 układów planetarnych generujących największy zysk netto, co pozwala wskazać najbardziej dochodowe kierunki wypraw. Kolumny <em>galaxy_name</em> oraz <em>planetary_system</em> identyfikują lokalizację danej trasy. <em>num_trips</em> to liczba odbytych wypraw, <em>total_cost</em> i <em>total_revenue</em> przedstawiają odpowiednio całkowite koszty i przychody związane z realizacją tych tras. <em>avg_planet_distance</em> wskazuje średnią odległość do planet w danym układzie. Na podstawie przychodów i kosztów obliczono również <em>net_profit</em> (zysk netto) oraz <em>profit_per_trip</em>, czyli średni zysk przypadający na jedną wyprawę.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Wykres “Zysk netto według galaktyk” ilustruje znaczącą koncentrację zysków w wybranych galaktykach. Galaktyka z najwyższym łącznym zyskiem netto to Polaris Nexus, generująca łącznie 7,178,102,797 USD. Najmniej zyskowną galaktyką jest Kronis Ring z łącznym zyskiem netto 1,189,546,052 USD.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>W top 5 galaktykach widać wyraźne różnice w zyskowności między układami planetarnymi. Można zauważyć, że w niektórych galaktykach pojedyncze układy dominują pod względem generowanego zysku, co sugeruje koncentrację atrakcyjnych celów wypraw.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Galaktyka o najwyższym średnim zysku na wyprawę to Kronis Ring, ze średnim zyskiem około 1,312,393 USD na wyprawę. To pokazuje, że efektywność pojedynczych wypraw różni się znacznie między galaktykami.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analiza wykazuje, że korelacja między odległością planet a liczbą wypraw wynosi 0.186, co sugeruje brak istotnej zależności. Oznacza to, że im dalej planeta od Ziemi, tym mniej wypraw jest do niej organizowanych.</p>
</section>
<section id="trendy-sezonowe-w-liczbie-wypraw-przychodach-oraz-ich-statusach" class="level1">
<h1>Trendy sezonowe w liczbie wypraw, przychodach oraz ich statusach</h1>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Największa liczba wypraw została zorganizowana w miesiącu styczeń, osiągając 12 wypraw. Z kolei najmniejszą liczbę wypraw odnotowano w miesiącu grudzień, z liczbą 1. Różnice te sugerują istnienie wyraźnej sezonowości w liczbie organizowanych wypraw.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Najwyższy miesięczny przychód odnotowano w miesiącu czerwiec, osiągając wartość 319 mln USD. Najniższy przychód przypadł na miesiąc październik, wynosząc 9 mln USD. To również może wskazywać na sezonowość przychodów.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Najwięcej zakończonych wypraw (<code>Completed</code>) odnotowano w miesiącu kwiecień, z liczbą 196 wypraw. Największa liczba opóźnionych wypraw (<code>Delayed</code>) wystąpiła w miesiącu marzec, osiągając 21 przypadków. W przypadku anulowanych wypraw (<code>Cancelled</code>) szczyt przypadł na miesiąc styczeń, luty, marzec, kwiecień, maj, czerwiec, lipiec, sierpień, wrzesień, październik, listopad, grudzień, gdzie naliczono 0 przypadków.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Największą liczbę wypraw zorganizowano w kwartale 1, osiągając wynik 31 wypraw. Z kolei najmniejszą liczbę wypraw zrealizowano w kwartale 4, zaledwie 10 wypraw.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>W tych samych okresach zauważalna jest również wyraźna zmienność przychodów.Najwyższy przychód firma osiągnęła w kwartale 2, generując 574,228,592 USD. Natomiast najniższy przychód zanotowano w kwartale 4, z wartością 122,275,931 USD.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Raport_Bazy_Danych_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Najwięcej zakończonych wypraw przypadło na kwartał 2, z liczbą 424. Największa liczba opóźnionych wypraw wystąpiła w kwartale 1, natomiast najwięcej anulowanych wypraw miało miejsce w kwartale - brak anulowanych wypraw.<br>
Takie dane pozwalają lepiej rozumieć problemy operacyjne oraz cykliczność niepowodzeń w realizacji wypraw.</p>
<p>Ciekawostką jest, że nie odnotowano żadnych anulowanych wypraw w żadnym miesiącu, co świadczy o bardzo wysokim poziomie operacyjnej niezawodności.</p>
</section>
<section id="podsumowanie" class="level1">
<h1>Podsumowanie</h1>
<p>W przeprowadzonej analizie wykorzystano relacyjną bazę danych firmy Space-U w celu pozyskania informacji o strukturze organizacyjnej, klientach oraz zasobach technicznych. Z pomocą języka SQL oraz pakietów R wykonano szereg zapytań i transformacji, umożliwiających ekstrakcję, agregację i wizualizację danych.</p>
<p>Efektem prac jest zestaw wniosków opartych na rzeczywistych danych, takich jak liczebność i zróżnicowanie zatrudnienia, aktywność klientów oraz stan techniczny i wykorzystanie rakiet. Analiza ujawnia m.in. potencjalne obszary do optymalizacji procesów oraz kierunki rozwoju operacyjnego.</p>
<p>Z punktu widzenia projektowania baz danych, raport potwierdza znaczenie poprawnej struktury schematu, spójnych typów danych i kluczy obcych dla zapewnienia integralności oraz wydajności zapytań. Proces analityczny pokazał również, że odpowiednia integracja narzędzi programistycznych (R + SQL) umożliwia szybkie i skalowalne uzyskiwanie informacji biznesowych na podstawie dużych wolumenów danych.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>